### ISSUE TITLE
module not working?

### ISSUE THREAD

**Issue by bafs84** [roufri/MMM-SwissLakeTemperature#1]
I followed the installation instructions and pasted the demo of lake Zurich, but as soon as I add the module into config.js, the MM is not reloading. 

Is the package still maintained?

**Comment by roufri** [comment]
> I followed the installation instructions and pasted the demo of lake Zurich, but as soon as I add the module into config.js, the MM is not reloading.
> 
> Is the package still maintained?

Hi, the module should still work as expected.

Did you check if your config file is valid?
https://forum.magicmirror.builders/topic/5399/how-to-check-your-config-for-errors-for-absolute-beginners

Also, you should not overwrite your whole config file with the one in the installation, you just add the module to the existing config.

For more specific errors, you can also check the dev console once you started the magic mirror.

Hope that helps.

**Comment by roufri** [comment]
> I followed the installation instructions and pasted the demo of lake Zurich, but as soon as I add the module into config.js, the MM is not reloading.
> 
> Is the package still maintained?

Never mind sorry I only now saw that they changed their API: https://www.alplakes.eawag.ch/api
Unfortunately I do not have time to fix this right now (will be another 6-9 months).
With the link above and little programming knowledge you could fix it yourself if you want (adapt the url for the API in https://github.com/roufri/MMM-SwissLakeTemperature/blob/c802106d7da9048b11fd9c3fb755e8a2ca26c402/MMM-SwissLakeTemperature.js#L63)

**Comment by lbartk** [comment]
Hi @bafs84 If you're still looking for a solution, I wrote a new module that uses the new API https://github.com/lbartk/MMM-SwissAlpLakes

**Comment by roufri** [comment]
@bafs84 I fixed the module by using the new API and updated the documentation (README).
Should be working now, else let me know.
